# Generated by Django 3.1.5 on 2021-01-30 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carspanel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='load_capacity',
        ),
    ]
