# Generated by Django 3.1.5 on 2021-01-31 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carspanel', '0002_remove_car_load_capacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='xcoord',
        ),
        migrations.RemoveField(
            model_name='car',
            name='ycoord',
        ),
        migrations.AddField(
            model_name='car',
            name='coords',
            field=models.CharField(default='', max_length=100),
        ),
    ]
