# Generated by Django 3.1.5 on 2021-01-31 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carspanel', '0003_auto_20210131_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='fe',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='car',
            name='sio2',
            field=models.IntegerField(default=0),
        ),
    ]
